## Config file for MR analysis
# snakemake -s mr.smk --configfile 3_Scripts/diab_config.yaml

DataIn: /Users/sheaandrews/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData/
#DataIn: /Users/shea/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData
TraitName: Type 2 Diabetes
TraitBlurb: "***Type 2 Diabetes*** [Xu et al Nature Genet 2018](https://www.nature.com/articles/s41467-018-04951-w):
  Here we conduct a meta-analysis of genome-wide association studies (GWAS) with
  ~16 million genetic variants in 62,892 T2D cases and 596,424 controls of
  European ancestry by combining 3 GWAS data sets of European ancestry: DIAbetes
  Genetics Replication and Meta-analysis (DIAGRAM), Genetic Epidemiology Research
  on Aging (GERA), and the full cohort release of the UK Biobank (UKB). We identify
  139 common and 4 rare variants associated with T2D, 42 of which (39 common and
  3 rare variants) are independent of the known variants."
TraitCode: diab
TraitClump: None
DataOut: 2_DerivedData/
Pthreshold: [5e-6, 5e-8]
