## Config file for MR analysis
# snakemake -s mr.smk --configfile 3_Scripts/load_config/hdl_config.yaml
# snakemake -s bmr.smk --configfile 3_Scripts/load_config/hdl_config.yaml

DataIn: 2_DerivedData/
TraitName: HDL Cholesterol
TraitBlurb: "***HDL Cholesterol*** [Willer et al Nat Genet 2013](https://www.nature.com/articles/ng.2797):
  To identify new loci and refine known loci influencing these lipids, we examined
  188,577 individuals using genome-wide and custom genotyping arrays. We identify
  and annotate 157 loci associated with lipid levels at P < 5 × 10−8, including
  62 loci not previously associated with lipid levels in humans."
TraitCode: hdl
TraitClump: None
DataOut: 2_DerivedData/
Pthreshold: [5e-6, 5e-8]
