## Config file for MR analysis
# snakemake -s mr.smk --configfile 3_Scripts/mdd_config.yaml

DataIn: /Users/sheaandrews/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData/
#DataIn: /Users/shea/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData
TraitName: Major Depressive Disorder
TraitBlurb: "***Major Depressive Disorder*** [Wray et al Nature Genet 2018](https://www.nature.com/articles/s41588-018-0090-3):
  The Psychiatric Genomics Consortium (PGC) conducted a GWAS meta-analysis across
  seven cohorts (PGC, deCODE, Generation Scotland, GERA, iPSYCH, UK Biobank, and
  23andMe) containing 130,664 MDD cases and 330,470 controls. Participants were
  of European Ancestry. "
TraitCode: mdd
TraitClump: None
DataOut: 2_DerivedData/
NbDistribution: 10000
Pthreshold: [5e-6, 5e-8]
Cache: TRUE
