## Config file for MR analysis
# snakemake -s mr.smk --configfile 3_Scripts/load_config/sociso_config.yaml
# snakemake -s bmr.smk --configfile 3_Scripts/load_config/sociso_config.yaml

DataIn: 2_DerivedData/
TraitName: Social Isolation
TraitBlurb: "***Social Isolation*** [Day et al Nat Commu 2018](https://www.nature.com/articles/s41467-018-04930-1):
  In up to 452,302 UK Biobank study participants, we perform genome-wide association
  study analyses for loneliness and identify 15 genomic loci (P < 5 × 10−8) for loneliness."
TraitCode: sociso
TraitClump: None
DataOut: 2_DerivedData/
Pthreshold: [5e-6, 5e-8]
