## Config file for MR analysis
## snakemake -s mr.smk --configfile 3_Scripts/load_config/alcc_config.yaml
## snakemake -s bmr.smk --configfile 3_Scripts/load_config/alcc_config.yaml
DataIn: /Users/sheaandrews/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData/
#DataIn: /Users/shea/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData
TraitName: Alcohol Consumption
TraitBlurb: "***Alcohol Consumption*** (Clarke et al 2017): SNPs associated with
alcohol consumption were selected from a GWAS of alcohol consumption (drinks per
week adjusted for sex, age and weight) performed in 112,117 individuals from the
UK Biobank [29]. Participants were of European ancestry, mean age was 59.6 and
52.7% of the cohort was female."
TraitCode: alcc
DataOut: 2_DerivedData/
TraitClump: None
Pthreshold: [5e-6, 5e-8]
