## Config file for MR analysis
# snakemake -s mr.smk --configfile 3_Scripts/load_config/sleep_config.yaml
# snakemake -s bmr.smk --configfile 3_Scripts/load_config/sleep_config.yaml

DataIn: 2_DerivedData/
TraitName: Sleep Duration
TraitBlurb: "***Sleep Duration*** [Lane et al Nat Genet 2017](https://www.nature.com/articles/ng.3749):
  We report single- and multiple-trait genome-wide association analyses of
  self-reported sleep duration, insomnia symptoms and excessive daytime sleepiness
  in the UK Biobank (n = 112,586)."
TraitCode: sleep
TraitClump: None
DataOut: 2_DerivedData/
Pthreshold: [5e-6]
