## Config file for MR analysis
# snakemake -s mr.smk --configfile 3_Scripts/audit_config.yaml
# snakemake -s bmr.smk --configfile 3_Scripts/audit_config.yaml

DataIn: /Users/sheaandrews/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData/
#DataIn: /Users/shea/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData
TraitName: AUDIT
TraitBlurb: "***AUDIT*** [Sanchez-Roige et al BioRxiv 2018](https://www.biorxiv.org/content/early/2018/08/02/275917):
  A GWAS of the Alcohol Use Disorder Identification Tes (AUDIT) was conducted in
  the British white individules in the UK Biobank. The GWAS meta-analysis with
  23andMe, identified 10 genome-wide significant loci with SNP-heritability of 12%."
TraitCode: audit
TraitClump: None
DataOut: 2_DerivedData/
Pthreshold: [5e-6, 5e-8]
