## Config file for MR analysis
# snakemake -s mr.smk --configfile 3_Scripts/educ_config.yaml

DataIn: /Users/sheaandrews/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData/
#DataIn: /Users/shea/Dropbox/Research/PostDoc-MSSM/2_MR/2_DerivedData
TraitName: Educational Atainment
TraitBlurb: "***Educational Attainment*** [Lee et al Nature Genet 2018](https://www.nature.com/articles/s41588-018-0147-3):
  Here we conducted a large-scale genetic association analysis of educational
  attainment in a sample of approximately 1.1 million individuals and identify
  1,271 independent genome-wide-significant SNPs."
TraitCode: educ
TraitClump: None
DataOut: 2_DerivedData/
Pthreshold: [5e-6]
